### ISSUE TITLE
Report mts warnings or errors after tileset creation

### ISSUE THREAD

**Issue by yuletide** [mapbox/mts-data-sync#4]
As a user, it would be helpful to know what, if any errors or warnings were created so I can fix them in my data or with additional recipe options.

For example: I try to tile some census data, the tool returns everything successful, but then my tiles have dropped features at some zoom levels. As a user I'm not sure how to check for those errors or fix them.

Proposed solution: 
* Provide a clickable link to check the status of the job, or report out in console any warnings

**Comment by jbranigan** [comment]
Fixed by #7
